config/routes.rb
Rails.application.routes.draw do
 
  #rutas oficinas
  get 'oficinas/listar', to: 'oficinas#listar'  , as: 'oficinas'
  get 'oficinas/crear', to: 'oficinas#crear'    
  post 'oficinas/guardar', to: 'oficinas#guardar'

  #rutas de iquilinos
  get 'inquilinos'            , to: 'inquilinos#listar'   , as: 'inquilinos'
  get 'inquilinos/crear'      , to: 'inquilinos#crear'    , as: 'nuevo_inquilino'
  get 'inquilinos/:id'        , to: 'inquilinos#mostrar'  , as: 'inquilino'
  get 'inquilinos/:id/editar'  , to: 'inquilinos#editar'  , as: 'editar_inquilino'



  post    'inquilinos'        , to: 'inquilinos#guardar'
  put     'inquilinos/:id'    , to: 'inquilinos#actualizar'
  patch   'inquilinos/:id'    , to: 'inquilinos#actualizar'
  delete  'inquilinos/:id'    , to: 'inquilinos#eliminar'


  root       to: 'sesiones#login'    , as: 'login'
  post      'sesiones'        , to: 'sesiones#iniciar'  
  delete    'sesiones'        , to: 'sesiones#cerrar'


end

app/models/administrador.rb
class Administrador < ApplicationRecord
    has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquilino.rb
class Inquilino < ApplicationRecord
  belongs_to :oficina

  after_save :verificar_disponibilidad_oficina
  after_destroy :verificar_disponibilidad_oficina

  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :telefono, presence: true
  
  validates :rut, presence: true
  validates :rut, uniqueness: true

  private 
  def verificar_disponibilidad_oficina
    puts "*******************************"
    if self.oficina.inquilinos.empty?
      self.oficina.esta_alquilada = false
    else
      self.oficina.esta_alquilada =true
    end
    self.oficina.save
  end
end

app/models/oficina.rb
class Oficina < ApplicationRecord
    
    has_many :inquilinos

    before_validation(:cambiar_a_mayusculas)
    
    
    validates :codigo, uniqueness: true
    validates :codigo, presence: true
    
    validates :precio, presence: true

    private
    def cambiar_a_mayusculas
        puts "=================="
        self.codigo.upcase!
        puts self.inspect
        puts "==================="
    end
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/inquilinos_controller.rb
class InquilinosController<ApplicationController
   before_action :validar_sesion
    before_action :buscar_inquilino, only:[:mostrar, :editar, :actualizar, :eliminar]


    def  listar
        @inquilino = Inquilino.includes(:oficina).order(id: :asc)
        
    end

    def mostrar

    end

    #get - devolver el formulario para crear un inquilino
    def crear
        @inquilino = Inquilino.new
        @oficinas = Oficina.select(:id, :codigo).order(codigo: :asc)
    end

    #post - recibir los datos de un inquilino y guardar en bdd
    def guardar
        @inquilino = Inquilino.new(inquilino_params)

        if @inquilino.save
            redirect_to "/oficinas/listar"
        else
            @oficinas = Oficina.select(:id, :codigo).order(codigo: :asc)
            render :crear
        end
    end
    
    #get
    def editar
        @oficinas = Oficina.select(:id, :codigo).order(codigo: :asc)
    end
    
    #put/patch
    def actualizar
       if @inquilino.update(inquilino_params)
            redirect_to inquilino_path
        else
            render :editar
        end
    end
    #DELETE
    def eliminar
        @inquilino.destroy
        redirect_to action: :listar
    end

    private
    def inquilino_params
        return params.require(:inquilino).permit(:nombre, :apellido, :telefono, :rut, :oficina_id)
    end

    def buscar_inquilino
        @inquilino = Inquilino.find(params[:id])
    end

end

app/controllers/oficinas_controller.rb
class OficinasController < ApplicationController
  
  before_action :validar_sesion
  
  def listar

    @lista_oficinas = Oficina.includes(:inquilinos).order(id: :asc)
    cookies.encrypted[:mi_galleta] = "de chocolate"
    
  end

  def crear
    @oficina_nueva = Oficina.new
  end

  def guardar
    valores = params.require(:oficina).permit(:codigo, :precio)
    @oficina_nueva = Oficina.new(valores)
    @oficina_nueva.esta_alquilada = false

    if @oficina_nueva.save
      redirect_to action:"listar"
    else
      render :crear
    end


  end

  

end

app/controllers/sesiones_controller.rb
class SesionesController < ApplicationController
    
    #get
    def login
        if session[:admin_id]
            redirect_to oficinas_path
        end
    end

    #post
    def iniciar
    # nombre_usuario_formulario = params[:nombre_usuario]
        admin = Administrador.find_by(nombre_usuario: params[:nombre_usuario])
            if admin and admin.authenticate(params[:password])
                
                session[:admin_id] = admin.id
                redirect_to oficinas_path
                    
            else
                    
                flash[:error_sesion] = "Nombre de usuario o contraseña incorrecto"
                render :login
                    
            end
    end

    #delete
    def cerrar

        session[:admin_id] = nil 
        redirect_to login_path

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def validar_sesion
        #obtener una coockie que se llama admin_id
        #si la cookie existe entonces
        #voy a buscar el usuario en la base de datos
        #crear variable con @admin ppara tenerla disponible
        if session[:admin_id]
            @admin = Administrador.find(session[:admin_id])
        else
            eliminar_cookie
        end

        rescue ActiveRecord::RecordNotFound
            eliminar_cookie
        end    
            private
            def eliminar_cookie
                session[:admin_id] = nil
                redirect_to sesiones_path
            end

end

app/helpers/oficinas_helper.rb
module OficinasHelper
end

app/views/inquilinos/_formulario.html.erb
 <h1>Ingreso de Inquilinos</h1>

<%= form_with(model: inquilino) do |formulario| %>


<div class="mb_3">
    <%= formulario.label :nombre , class: 'form-label'%>
    <%= formulario.text_field :nombre, class: 'form-control' %>
    <% if inquilino.errors[:nombre].any? %>

        <div style="color: red">

            <%= inquilino.errors[:nombre].first %>

        </div>

    <% end %>
</div>


    
<div class="mb_3">
    <%= formulario.label :apellido , class: 'form-label'%>

    <%= formulario.text_field :apellido, class: 'form-control' %>

    <% if inquilino.errors[:apellido].any? %>
<div style="color: red">
        <%= inquilino.errors[:apellido].first %>
</div>
    <% end %>
</div>
    


<div class="mb_3">
    <%= formulario.label :telefono , class: 'form-label'%>

    <%= formulario.text_field :telefono, class: 'form-control' %>

    <% if inquilino.errors[:telefono].any? %>
<div style="color: red">
        <%= inquilino.errors[:telefono].first %>
</div>
    <% end %>
</div>
    


<div class="mb_3">
    <%= formulario.label :rut , class: 'form-label'%>

    <%= formulario.text_field :rut , class: 'form-control'%>

    <% if inquilino.errors[:rut].any? %>
<div style="color: red">
        <%= inquilino.errors[:rut].first %>
</div>
    <% end %>
</div>
    


<div class="mb-3">
    <%= formulario.label :oficina_id, class: 'form-label' %>
    <%  if inquilino.oficina %> <!--evalua si existe una oficina para inquilino -->
        
    <%= formulario.select :oficina_id, 
        options_from_collection_for_select(oficina, :id, :codigo, inquilino.oficina.id) , {},
        {class: 'form-select'}
        %>
    <% else %>
        
    <%= formulario.select :oficina_id, 

        options_from_collection_for_select(oficina, :id, :codigo) {},
        {class: 'form-select'}
        %>
    <% end %>
</div>


    <%= formulario.submit 'Registrar inquilino' , class: 'btn btn-primary' %>

<% end %>

app/views/inquilinos/_tarjeta_inquilino.html.erb
 <h1>Ingreso de Inquilinos</h1>

<%= form_with(model: inquilino, url: '/inquilinos/crear') do |formulario| %>


<div class="mb_3">
    <%= formulario.label :nombre , class: 'form-label'%>
    <%= formulario.text_field :nombre, class: 'form-control' %>
    <% if inquilino.errors[:nombre].any? %>

        <div style="color: red">

            <%= inquilino.errors[:nombre].first %>

        </div>

    <% end %>
</div>


    
<div class="mb_3">
    <%= formulario.label :apellido , class: 'form-label'%>

    <%= formulario.text_field :apellido, class: 'form-control' %>

    <% if inquilino.errors[:apellido].any? %>
<div style="color: red">
        <%= inquilino.errors[:apellido].first %>
</div>
    <% end %>
</div>
    


<div class="mb_3">
    <%= formulario.label :telefono , class: 'form-label'%>

    <%= formulario.text_field :telefono, class: 'form-control' %>

    <% if inquilino.errors[:telefono].any? %>
<div style="color: red">
        <%= inquilino.errors[:telefono].first %>
</div>
    <% end %>
</div>
    


<div class="mb_3">
    <%= formulario.label :rut , class: 'form-label'%>

    <%= formulario.text_field :rut , class: 'form-control'%>

    <% if inquilino.errors[:rut].any? %>
<div style="color: red">
        <%= inquilino.errors[:rut].first %>
</div>
    <% end %>
</div>
    


<div class="mb-3">
    <%= formulario.label :oficina_id, class: 'form-label' %>

    <%= formulario.select :oficina_id, 

        options_from_collection_for_select(oficina, :id, :codigo, inquilino.oficina.id) , {},
        {class: 'form-select'}
        %>
</div>


    <%= formulario.submit 'Registrar inquilino' , class: 'btn btn-primary' %>

<% end %>

app/views/inquilinos/crear.html.erb
<h2>crear inquilino</h2>


<%= render 'formulario', inquilino: @inquilino, oficina: @oficinas%>

app/views/inquilinos/editar.html.erb
<h2>editar inquilino</h2>

<%= render 'formulario', inquilino: @inquilino, oficina: @oficinas%>

app/views/inquilinos/listar.html.erb
<h1>Inquilinos Registrados</h1>

<%= link_to 'Nuevo Inquilino', "inquilinos/crear" %>


<table class="table table-hover">

<thead>
    <tr>
        <th scope="col">Id </th>
        <th scope="col">Nombre</th>
        <th scope="col">Apellido </th>
        <th scope="col">Telefono</th>
        <th scope="col">Rut </th>
        <th scope="col">Oficina </th>
        <th scope="col">Acciones </th>
    </tr>
</thead>

<tbody>

<% @inquilino.each do |inquilino| %>
    <tr>
        <td> <%= inquilino.id %></td>
        <td> 
        <!--   <a href="inquilinos/<%= inquilino.id %>"> <%= inquilino.nombre %></a> -->
        <%= link_to inquilino.nombre, inquilino_path(inquilino) %>
        </td>
        <td><%= inquilino.apellido %></td>
        <td><%= inquilino.telefono %></td>
        <td> <%= inquilino.rut %></td>
        <td><%= inquilino.oficina.codigo %></td>
        <td>
        <%= link_to 'Editar', editar_inquilino_url(inquilino) %> / 
        <%= link_to 'Eliminar', inquilino_path(inquilino), method: :delete, data: {confirm: 'seguro que quiere borrar el inquilino?'} %> 
        </td>
    </tr>
<% end %>

</tbody>
</table>

app/views/inquilinos/mostrar.html.erb
<br><br><br>

<%= @inquilino.id %>
<%= @inquilino.nombre %>
<%= @inquilino.apellido %>
<%= @inquilino.telefono %>
<%= @inquilino.rut %>
<%= @inquilino.oficina.codigo %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oficinas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/sesiones.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oficinas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
  </body>
</html>

app/views/oficinas/_tarjeta_oficina.html.erb
<!--
    <p>  Oficina  Nº <%= oficina.codigo %>  
    <br>
        <span> Valor: </span>
        <%= oficina.precio %> 
    </p>
            
            
        <% if oficina.inquilinos.empty? %>
            <p>Disponible</p>
        <% else %>
            <span> Alquilado por: </span>
                <ul>
                    <% oficina.inquilinos.each do |inquilino| %>
                        <li>
                            <%= inquilino.nombre + " " + inquilino.apellido %>
                        </li>
                    <% end %>    
                </ul>
            <% end %>
    
    <hr>
    -->


    <div class="card" style="width: 18rem; margin-top_ 1em;"> 
        <div class="card-body">
            <h5 class="card-title">Oficina Nº <%= oficina.codigo %> </h5>
            <p class="card-text">Valor: <%= oficina.precio %></p>
            <% if oficina.inquilinos.empty? %>
                <p>Disponible</p>
            <% else %>
                <span> Alquilado por: </span>
                    <ul>
                        <% oficina.inquilinos.each do |inquilino| %>
                            <li>
                                <%= inquilino.nombre + " " + inquilino.apellido %>
                            </li>
            <% end %>    
                    </ul>
                    <% end %>
        
            <a href="#" class="btn btn-primary">Modificar</a>
            <a href="#" class="btn btn-warning">Borrar Inquilinos</a>
        </div>
    </div>

app/views/oficinas/crear.html.erb
<h1>Crear una nueva oficina para alquilar</h1>

<%= form_with(model: @oficina_nueva, url: '/oficinas/guardar') do |formulario| %>
    <%if @oficina_nueva.errors.any? %>
        <% @oficina_nueva.errors.each do |error| %>
            <p style="color:red;"> <%= error.full_message %></p>
        <%end %>
    <% end %>
    
        <%= formulario.label :codigo %>
        <%= formulario.text_field :codigo %>
    <br>
        <%= formulario.label :precio %>
        <%= formulario.text_field :precio %>
    <br>
    

        <%= formulario.submit 'Crear Oficina' %>
<%end%>

<a >

app/views/oficinas/listar.html.erb
<% @lista_oficinas.each do |ofi| %>

<%= render 'tarjeta_oficina', oficina: ofi %>

<%end %>


<a href="/oficinas/crear">volver a crear</a>


<!--cookies.delete :admin_id
        redirect_to login_path-->

app/views/sesiones/login.html.erb
<div class="container">

    <h1>Iniciar Sesion</h1>

    <% if flash[:error_sesion]  %>
        <div class="alert alert-danger" role="alert">
            <%= flash[:error_sesion] %>
        </div>
    <%end %>

    <%= form_with(url: 'sesiones') do |formulario| %>
        <div class="mb-3">
            <%= formulario.label :nombre_usuario, class: 'form-label' %>
            <%= formulario.text_field :nombre_usuario, class: 'form-controller' %>
        </div>   

        <div class="mb-3">   
            <%= formulario.label :password, class: 'form-label' %>
            <%= formulario.password_field :password, class: 'form-controller' %>

        </div>   

        <div>
    <%= formulario.submit 'iniciar sesion', class: 'tbn btn-primary' %>
    <% end %>

</div>